### ISSUE TITLE
What is meant by uproot not being useful if you have collections in your root files?

### ISSUE THREAD

**Issue by meliache** [kqf/root-recipes#1]
Uproot can deal with trees with leaves that contain vectors or other classes which contain numbers or vectors of numbers. Here is an example on how to read data from root files with `TLorentzVector`s:
https://github.com/scikit-hep/awkward-array#lhc-data-from-a-root-file. Also it should be able to interpret many simple custom dataclasses, as explained on [stackoverflow](https://stackoverflow.com/questions/58640970/how-to-access-custom-classes-with-uproot). However, I assume you can't use the methods of `TLorentzVector`, uproot is only for IO.

> It's not a matter of handling every class on a class-by-class basis, it's about handling class features. For instance, the most recent addition was classes containing vectors of numbers. If you have classes with very conservative contents, such as "only numeric fields," then it should be automatically identified.

Tt can't interpret all kinds of C++ classes, but I am not sure it is fair to say that it is not useful for collections. Tbh I haven't used it much for that, mostly for reading NTuples into dataframes, but as I understand the documentation it is very versatile.

**Comment by kqf** [comment]
Hey, thanks for your point. The text refers to `TCollections`. Let say you have this code: 
```python
# example.py
import ROOT


def main():
    olist = ROOT.THashList()
    for i in range(10):
        hist = ROOT.TH1F(f"hist_{i}", "", 100, -3, 10)
        hist.FillRandom("landau")
        olist.Add(hist)

    ofile = ROOT.TFile("example.root", "recreate")
    ofile.cd()
    olist.Write("selections", ROOT.TObject.kSingleKey)
    ofile.Close()


if __name__ == '__main__':
    main()

```
The produced file causes an error while trying to read with uproot on my remote server:
```
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/uproot/rootio.py", line 59, in open
    return ROOTDirectory.read(localsource(path), **options)
  File "/usr/local/lib/python3.6/site-packages/uproot/rootio.py", line 140, in read
    classes = _defineclasses(streamerinfos)
  File "/usr/local/lib/python3.6/site-packages/uproot/rootio.py", line 703, in _defineclasses
    code.insert(0, "class {0}({1}):".format(_safename(streamerinfo.fName), ", ".join(bases)))
TypeError: sequence item 1: expected str instance, bytes found
```

You can reproduce this issue:
```bash
# local machine
python example.py

# Create the environment 
docker run -it --rm -v ${PWD}:/home/ -w /home python:3.6 bash

# Inside the container env
pip install uproot==2.5.0

# Gives an error
python -c 'import uproot; print(uproot.open("example.root")["selections"])'
```
However, I just tried the latest version of `uproot` in the container environment and it actually works. It's still not usable in my case (frozen envs.), but it's not related to the subject. Anyways, thanks, I will update the description.
